apiVersion: v1
kind: Pod
metadata:
  name: Configpod
  labels:
    project: roboshop
    environ: dev
  
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: config-map