apiVersion: v1
kind: Pod
metadata:
  name: secretpod
  labels:
    project: roboshop
    environ: dev
  
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "200Mi"
      envFrom:
        - secretRef:
            name: nginx-secret

    - name: busybox
      image: busybox
      command: ["sleep", "1000"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "200Mi"