apiVersion: v1
kind: Service 
metadata: 
  name: service-lb 
  labels: 
    project: roboshop
    env: dev

spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: nginx

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
     